[package]
name = "js_option"
version = "0.1.0"
authors = ["Jonas Platte <jonas@lumeo.com>"]
license = "MIT"
edition = "2018"
resolver = "2"

[features]
default = ["serde"]
serde = ["serde_crate"]

[dependencies]
serde_crate = { package = "serde", version = "1.0.125", optional = true }

[dev-dependencies]
serde_crate = { package = "serde", version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
