name: Git Checks

on: [pull_request]

jobs:
  block-fixup:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v5
    - name: Check fixup commits. Rebase w/ autosquash required if this fails.
      uses: 13rac1/block-fixup-merge-action@v2.0.0
