name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v5
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Catch common mistakes
      run: cargo clippy --all-targets -- -D warnings
